default:
  image: "python:3.12.11-trixie"

create-pages:  # a user-defined job that builds your pages and saves them to the specified path.
  script:
    - make build
  pages: true  # specifies that this is a Pages job
  artifacts:
    paths:
      - site
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production
