site_name: Doors in the Wild
theme: readthedocs
nav:
  - Home: README.md
  - Tradecraft:
    - Access Conrol: dbac.md
    - Linting: linting.md
    - Payload Polymorphism: payload_polymorphism.md
    - Static File Descriptors: static_file_descriptor.md
    - Switching Tables: switching_table.md
  - Sightings:
    - auditd: auditd.md
    - bridged: bridged.md
    - devfsadm: devfsadm.md
    - dlmgmtd: dlmgmtd.md
    - drd: drd.md
    - fmd: fmd.md
    - ikeadm: ikeadm.md
    - ipmgmt: ipmgmt.md
    - nwamd: nwamd.md
    - syseventd: sysevent.md
    - wpad: wpa_supplicant.md
  - Miscellany:
    - Interesting: interesting.md
    - Not Interesting: not_interesting.md
