site_name: Doors in the Wild
theme: readthedocs
nav:
  - Home: README.md
  - Tradecraft:
    - Access Control: dbac.md
    - Door Return Failure: door_return_failure.md
    - Linting: linting.md
    - Liveness Check: liveness_check.md
    - Payload Polymorphism: payload_polymorphism.md
    - Preventing Thread Cancellation: thread_cancellation.md
    - Static File Descriptors: static_file_descriptor.md
    - Switching Tables: switching_table.md
  - Sightings:
    - auditd: auditd.md
    - automountd: automountd.md
    - bridged: bridged.md
    - devfsadm: devfsadm.md
    - dlmgmtd: dlmgmtd.md
    - drd: drd.md
    - fmd: fmd.md
    - hotplugd: hotplugd.md
    - ibd: ibd.md
    - idmapd: idmapd.md
    - ikeadm: ikeadm.md
    - ipmgmtd: ipmgmtd.md
    - mountd: mountd.md
    - nfsmapid: nfsmapid.md
    - nwamd: nwamd.md
    - reparsed: reparsed.md
    - smbiod: smbiod.md
    - syseventd: sysevent.md
    - wpad: wpa_supplicant.md
  - Miscellany:
    - Interesting: interesting.md
    - Not Interesting: not_interesting.md
